### ISSUE TITLE
Skullstripping failure for 7T MP2RAGE anat

### ISSUE THREAD

**Issue by xingyu-liu** [pBFSLab/DeepPrep#103]
Hi!

DeepPrep is such a wonderful project, thank you so much for developing it!

When I used it to preprocess a 7T dataset that has MP2RAGE T1w, the skullstripping failed to cover the whole brain (shown in pic below, red denotes the brain mask DeepPrep produces).
 
<img width="527" alt="image" src="https://github.com/pBFSLab/DeepPrep/assets/31683843/5517b0a6-3b2e-4251-8a8c-7b299246f2e2">

I'va also tried a pre-skullstripping before sending it to DeepPrep, but it still failed. 

Any idea on that? 

Thanks!
Xingyu

**Comment by NingAnMe** [comment]
Hi, @xingyu-liu,
DeepPrep doesn't handle 7T data very effectively. We're planning to address this in our upcoming work.
