### ISSUE TITLE
Support set multiple task-labels with --bold_task_type

### ISSUE THREAD

**Issue by NingAnMe** [pBFSLab/DeepPrep#107]
As mentioned in  #104.
for example:
--bold_task_type 'taska taskb taskc'

**Comment by NingAnMe** [comment]
> In the same vein, could you also make it possible for multiple participants for --participant-label? Sometimes one might run some subj for test and rest of them afterwards.

for example:
1) --bold_task_type 'taska taskb taskc'   --participant_label '01 02 03'

2) --bold_task_type 'taskb taskc'   --participant_label '04 05'

In the end, It can run multiple times like this.

**Comment by lincong8722** [comment]
Hi @xingyu-liu, 

Our latest version is now compatible with multi tasks, you can clone the latest code or pull the latest docker `pbfslab/deepprep:23.1.8`.
Sample command: `--bold_task_type 'taska taskb taskc'` 

Feel free to reach out if you have any questions!

**Comment by xingyu-liu** [comment]
Got it! Thank you so much!
