### ISSUE TITLE
Question about the confounds `confounds_series.txt` file

### ISSUE THREAD

**Issue by julfou81** [pBFSLab/DeepPrep#111]
Hi,

Thank you for providing this very nice tool!
I use DeepPrep on a HPC with singularity and GPU and so far, so good! I have a question about the column labels in the file `desc-confounds_timeseries.txt` : What do they mean? Are `compX` the values of aCompCor components? If yes, where are they calculated? WM, CSF? Combined mask of WM and CSF?

` Frame dL dP dS pitch yaw roll dL_d dP_d dS_d pitch_d yaw_d roll_d WB WB_d vent vent_d wm wm_d comp1 ... `

Thank you!

**Comment by Ireneyou33** [comment]
Hi, 

The explanations are provided below, hope you find this helpful :)

1. `Frame:` the current frame of BOLD.

2. The first 6 parameters are the original head motion parameters (`6HMP`).
`dL:` translational displacement in the left direction (X-axis)
`dP:` translational displacement in the posterior direction (Y-axis)
`dS:` translational displacement in the superior direction (Z-axis)
`pitch:` rotation around the pitch-axis (right/left)
`yaw:` rotation around the yaw-axis (anterior/posterior)
`roll:` rotation around the roll-axis (inferior/superior)

3. The following 6 parameters (`dL_d`, `dP_d`, `dS_d`, `pitch_d`, `yaw_d`, `roll_d`) are the temporal derivatives of each of the original `6HMP`, resulting in 12 head motion parameters (`12HMP`) in total.

4. The `WB`, `vent`, and `wm` represent the within brainmask signal, ventrical signal, and white matter signal, while the `WB_d`, `vent_d`, and `wm_d` are their corresponding temporal derivatives.

5. The last 10 parameters (`comp1`-`comp10`) correspond to the first 10 PCA components of the signal outside the brainmask.
