### ISSUE TITLE
Feature Request: Allow None as a Valid Option for --bold_surface_spaces and --bold_volume_space

### ISSUE THREAD

**Issue by xingyu-liu** [pBFSLab/DeepPrep#115]
I'd like to propose the addition of None as a valid option for the `--bold_surface_spaces` and `--bold_volume_space` command-line arguments. This feature will provide flexibility for users who need outputs exclusively in either surface or volume spaces, not both.

Thank you so much!
Best,
Xingyu

**Comment by lincong8722** [comment]
Hi! @xingyu-liu ,

We have added the function of (--bold_surface_spaces) or (--bold_volume_space) to None in the new version of the code. You can pull the latest version of the code or docker for testing.
