### ISSUE TITLE
crushed during 'anat_wf:anat_create_summary'

### ISSUE THREAD

**Issue by xingyu-liu** [pBFSLab/DeepPrep#129]
Hi!

I've been recenely encountered with this error no for whatever datasets. Here is the error log for the sample dataset you provide.

> ERROR ~ Error executing process > 'anat_wf:anat_create_summary (sub-01)'
> 
> Caused by:
>   Process `anat_wf:anat_create_summary (sub-01)` terminated with an error exit status (1)
> 
> Command executed:
> 
>   qc_create_summary.py     --bids_dir /data     --subjects_dir /output/test_sample_deepprep/Recon     --subject_id sub-01     --template_space "NONE"     --qc_result_path /output/test_sample_deepprep/QC     --deepprep_version 23.1.0     --nextflow_log /output/test_sample_deepprep/WorkDir/nextflow/.nextflow.log
> 
> Command exit status:
>   1
> 
> Command output:
>   240515-21:08:20,898 nipype.workflow INFO:
>          [Node] Setting-up "T1w_Reports_run_node" in "T1w_Reports_run_node".
>   240515-21:08:20,899 nipype.workflow INFO:
>          [Node] Executing "T1w_Reports_run_node" <reports.reports_node.TemplateDimensions>
>   240515-21:08:20,927 nipype.workflow INFO:
>          [Node] Finished "T1w_Reports_run_node", elapsed time 0.020078s.
> 
> Command error:
>   240515-21:08:20,898 nipype.workflow INFO:
>          [Node] Setting-up "T1w_Reports_run_node" in "T1w_Reports_run_node".
>   240515-21:08:20,899 nipype.workflow INFO:
>          [Node] Executing "T1w_Reports_run_node" <reports.reports_node.TemplateDimensions>
>   240515-21:08:20,927 nipype.workflow INFO:
>          [Node] Finished "T1w_Reports_run_node", elapsed time 0.020078s.
>   Traceback (most recent call last):
>     File "/opt/DeepPrep/deepprep/nextflow/bin/qc_create_summary.py", line 140, in <module>
>       TemplateDimensions_run(args.subject_id, t1w_files, qc_result_path)
>     File "/opt/DeepPrep/deepprep/nextflow/bin/qc_create_summary.py", line 78, in TemplateDimensions_run
>       shutil.copyfile(Path(node_name) / 'report.html',
>     File "/usr/lib/python3.10/shutil.py", line 256, in copyfile
>       with open(dst, 'wb') as fdst:
>   FileNotFoundError: [Errno 2] No such file or directory: '/output/test_sample_deepprep/QC/sub-01/figures/sub-01_desc-templatedimensions_report.html'
> 
> Work dir:
>   /output/test_sample_deepprep/WorkDir/nextflow/c3/abb69ba18c7c4b10a8b667b2ac7dbc
> 
> Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
> 
>  -- Check '.nextflow.log' file for details

Any idea on this? Thanks!

Best,
Xingyu

**Comment by JChRoy** [comment]
Hi Xingyu, 

I had the same issue by cloning  pBFSLab/DeepPrep.git
Using git clone https://github.com/IndiLab/DeepPrep.git which does not have this process enables to move forward. 

Best, 
Jean-Charles

**Comment by xingyu-liu** [comment]
Got it. Thank you very much!
